server:
  port: 8081

security:
  oauth2:
    resource:
      token-info-uri: "${AUTH_SERVER_URI}/oauth/check_token"
      id: "dev-resource"
    client:
      client-id: "${CLIENT_ID}"
      client-secret: "${CLIENT_SECRET}"