spring:
  application:
    name: oauth2-auth-server
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: "${JDBC_URL}"
    username:  "${JDBC_USERNAME}"
    password: "${JDBC_PASSWORD}"
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    mongodb:
      host: "${MONGO_HOST}"
      database: "${MONGO_DATABASE}"
      username: "${MONGO_USERNAME}"
      password: "${MONGO_PASSWORD}"
      authentication-database: "${MONGO_AUTH_DATABASE}"
      port: 27017
  h2:
    console:
      enabled: true


server:
  port: 8090

